import { Book } from './types';

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: '클린 코드 (Clean Code)',
    author: '로버트 C. 마틴',
    price: 25000,
    originalPrice: 40000,
    condition: 'Like New',
    description: '한 번 읽고 보관만 해서 상태 아주 좋습니다. 밑줄이나 필기 전혀 없습니다. 개발자 필수 도서입니다.',
    images: ['https://picsum.photos/400/600?random=1'],
    sellerId: 'user1',
    sellerName: '개발왕김코딩',
    location: '서울 강남구',
    createdAt: Date.now() - 10000000,
    likes: 12,
  },
  {
    id: '2',
    title: '위대한 개츠비 (문학동네)',
    author: 'F. 스콧 피츠제럴드',
    price: 8000,
    originalPrice: 15000,
    condition: 'Good',
    description: '표지에 약간의 생활 기스는 있지만 내부는 깨끗합니다. 소장용으로 좋습니다.',
    images: ['https://picsum.photos/400/600?random=2'],
    sellerId: 'user2',
    sellerName: '책벌레99',
    location: '부산 해운대구',
    createdAt: Date.now() - 50000000,
    likes: 5,
  },
  {
    id: '3',
    title: 'Introduction to Algorithms (알고리즘 개론)',
    author: 'Thomas H. Cormen',
    price: 55000,
    originalPrice: 120000,
    condition: 'New',
    description: '비닐도 뜯지 않은 새 책입니다. 전공 수업 들으려다 드랍해서 팝니다. 4판입니다.',
    images: ['https://picsum.photos/400/600?random=3'],
    sellerId: 'user3',
    sellerName: '컴공학생',
    location: '서울 마포구',
    createdAt: Date.now() - 200000,
    likes: 45,
  },
  {
    id: '4',
    title: '사피엔스',
    author: '유발 하라리',
    price: 18000,
    originalPrice: 22000,
    condition: 'Like New',
    description: '선물 받고 한 번도 안 읽은 새 책 수준입니다.',
    images: ['https://picsum.photos/400/600?random=4'],
    sellerId: 'user4',
    sellerName: '역사덕후',
    location: '경기 성남시',
    createdAt: Date.now() - 3600000,
    likes: 28,
  },
  {
    id: '5',
    title: '해리포터와 마법사의 돌 (미나리마 에디션)',
    author: 'J.K. 롤링',
    price: 35000,
    originalPrice: 48000,
    condition: 'New',
    description: '미나리마 에디션 팝업북입니다. 소장용으로 샀다가 공간 부족으로 팝니다.',
    images: ['https://picsum.photos/400/600?random=5'],
    sellerId: 'user5',
    sellerName: '마법사',
    location: '서울 서초구',
    createdAt: Date.now() - 86400000,
    likes: 99,
  },
  {
    id: '6',
    title: '총 균 쇠',
    author: '재레드 다이아몬드',
    price: 15000,
    originalPrice: 28000,
    condition: 'Fair',
    description: '형광펜 밑줄 좀 있습니다. 공부하실 분 싸게 가져가세요.',
    images: ['https://picsum.photos/400/600?random=6'],
    sellerId: 'user1',
    sellerName: '개발왕김코딩',
    location: '서울 강남구',
    createdAt: Date.now() - 120000000,
    likes: 2,
  },
  {
    id: '7',
    title: '돈의 속성',
    author: '김승호',
    price: 10000,
    originalPrice: 16800,
    condition: 'Good',
    description: '재테크 입문 필독서입니다. 상태 양호합니다.',
    images: ['https://picsum.photos/400/600?random=7'],
    sellerId: 'user6',
    sellerName: '부자될거야',
    location: '대구 수성구',
    createdAt: Date.now() - 400000,
    likes: 15,
  },
  {
    id: '8',
    title: '파친코 1',
    author: '이민진',
    price: 9000,
    originalPrice: 15000,
    condition: 'Like New',
    description: '드라마 보고 원작 읽고 싶어서 샀습니다. 정말 재밌어요.',
    images: ['https://picsum.photos/400/600?random=8'],
    sellerId: 'user7',
    sellerName: '드라마광',
    location: '인천 연수구',
    createdAt: Date.now() - 50000,
    likes: 8,
  },
  {
    id: '9',
    title: '코스모스',
    author: '칼 세이건',
    price: 22000,
    originalPrice: 35000,
    condition: 'Good',
    description: '벽돌책이라 다 못 읽고 팝니다... 앞부분만 좀 폈어요.',
    images: ['https://picsum.photos/400/600?random=9'],
    sellerId: 'user8',
    sellerName: '우주먼지',
    location: '대전 유성구',
    createdAt: Date.now() - 10000,
    likes: 4,
  },
  {
    id: '10',
    title: '미움받을 용기',
    author: '기시미 이치로',
    price: 8000,
    originalPrice: 14900,
    condition: 'Fair',
    description: '오래된 책이라 변색이 좀 있습니다. 읽는 데는 지장 없어요.',
    images: ['https://picsum.photos/400/600?random=10'],
    sellerId: 'user9',
    sellerName: '심리학도',
    location: '광주 동구',
    createdAt: Date.now() - 999999,
    likes: 1,
  },
];